apiVersion: apps/v1
kind: Deployment
metadata:
  name: skarbek-dev
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: localhost:32000/skarbek-dev:registry
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: skarbek-dev
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: webserver

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: skarbek-dev-tls
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`skarbek.dev`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: skarbek-dev
      port: 80
  tls:
    certResolver: letsencrypt
