version: '3'

services:
  server:
    image: web:server
    container_name: server
    build:
      context: .
    working_dir: /app
    entrypoint:
      - /app/web-server
    privileged: true
    ports:
      - 80:8080
      - 443:8443
    devices:
      - '/dev/i2c-1:/dev/i2c-1'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './web:/app/web'
      - './db:/app/db'
      - './creds.json:/app/creds.json'
